default: &default
  adapter: postgresql
  host: localhost
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql

